# FV-CNN configuration for CUReT (image-level classification)

# dataset
dataset: smohsensadeghi/curet-dataset
deeper_path: CUReT/curetgrey/
resize: 200
train_ratio: 0.5
test_ratio: 0.15
train_val_ratio: 2
seed: 42
num_classes: 61

# feature extractor
framework: fvcnn
backbone: vgg16
feature_layer: conv5_3

# multi-scale
# scales = 2 ** s, where s = [-3, -2.5, -2, ... 1.5]
scales: [0.125, 0.17677670, 0.25, 0.35355339, 0.5, 0.70710678, 1., 1.41421356, 2., 2.82842712]
min_edge: 30
max_sqrt_hw: 1024

# IFV encoder
encoder_type: fv
gmm_components: 64
gmm_samples: 1.0e+4
gmm_batch_size: 128
pca_dim: null
signed_sqrt: true
l2_normalize: true

# training
batch_size: 32
svm_C: 1.0
svm_calibration: false
