# FV-CNN configuration for KTH-TIPS2b (image-level classification)

# dataset
dataset: kthtips2b
root_dir: data/datasets/KTH-TIPS2-b
fold: 0
resize: 200
train_ratio: 1.0
test_ratio: 0.15
drop_last: false
seed: 42
num_classes: 11

# feature extractor
framework: fccnn
backbone: vgg11
feature_layer: fc7

# preprocessing
preprocess_mode: imagenet
matconvnet_mean: auto # [123.68, 116.779, 103.939]

# region handling
region_mode: none
region_size: 128
region_stride: 64
region_border: 0.0
region_pooling: mean

# multi-scale
scales: [2.82842712, 2.0, 1.41421356, 1.0, 0.70710678, 0.5, 0.35355339, 0.25, 0.17677670, 0.125]
min_edge: 30
max_sqrt_hw: 1024

# IFV encoder
encoder_type: none
gmm_components: 64
gmm_reservoir_size: 200000
gmm_max_desc_per_image: null
gmm_memmap_path: null
gmm_memmap_size: null
gmm_memmap_cleanup: true
local_pca_dim: null
local_whitening: false
local_whitening_regul: 0.0
local_pca_fit_samples: 200000
pca_dim: null
signed_sqrt: true
l2_normalize: true

# training
batch_size: 16
svm_C: 1.0
svm_calibration: false

# logging
vmap_chunk_size: 2
