# FV-CNN configuration for Outex-12 (image-level classification)
# Mirrors dataset split settings from configs_wph, with FV-CNN specific params.

# dataset settings
dataset: outex12
root_dir: data/datasets/Outex-TC-00012-bmp
resize: 128
train_ratio: 0.5
test_ratio: 0.15
train_val_ratio: 2
fold: 0
seed: 42
num_classes: 24

# feature extractor
framework: fccnn           # fvcnn | fccnn
backbone: vgg16            # alexnet | resnet50 | vgg16
feature_layer: fc7     # conv5_3 (VGG-16), conv5 (AlexNet), layer4 (ResNet50)
# for FC-CNN set feature_layer to: fc7 (AlexNet/VGG), avgpool (ResNet50)

# multi-scale settings (Cimpoi-style)
scales: [1.4142, 1.0, 0.7071, 0.5, 0.3536, 0.25, 0.1768, 0.125, 0.0884, 0.0625]
min_edge: 30
max_sqrt_hw: 1024

# IFV encoder settings
encoder_type: fv           # fv only for this framework
gmm_components: 64         # K
pca_dim: null              # optional PCA dims (null => no PCA)
signed_sqrt: true
l2_normalize: true

# training
batch_size: 32
svm_C: 1.0
svm_calibration: false     # optional median-shift calibration

# logging
vmap_chunk_size: 50
