# model setting
wavelet: morlet
max_scale: 2
nb_orients: 4
efficient: true

# training setting
dataset: roustoumabdelmoula/textures-dataset
deeper_path: ''
resize: 300
classifier_epochs: 1
conv_epochs: 1
batch_size: 200
lr: 0.001
lambda_reg: 1e-5
train_ratio: 0.9
val_ratio: 0.1

