# model setting
wavelet: morlet
max_scale: 5
nb_orients: 4
num_phases: 2
num_phases_prime: 1
random_filters: false
share_rotations: false
share_channels: true
share_phases: false
normalize_relu: true
delta_j: null
delta_l: null
shift_mode: samec
mask_union: false
mask_angles: 4
mask_union_highpass: true

# training setting
dataset: smohsensadeghi/curet-dataset
deeper_path: CUReT/curetgrey/
resize: 200
classifier_epochs: 15
conv_epochs: 10
batch_size: 32
lr: 0.00001
lambda_reg: 1.0e-5
train_ratio: 0.9
train_size: None
val_ratio: 0.1
seed: 42
vmap_chunk_size: 50

# Classifier settings
num_classes: 61
use_batch_norm: true

