# model setting
wavelet: morlet
max_scale: 5
nb_orients: 4
num_phases: 2
num_phases_prime: 1
random_filters: false
share_rotations: false
share_channels: true
share_phases: false
normalize_relu: true
delta_j: null
delta_l: null
shift_mode: samec
mask_union: false
mask_angles: 4
mask_union_highpass: true
share_scales: false
downsample: true
share_scale_pairs: true
wavelet_params:
  S: 15
  T: 8
  w0: 2.7646
spatial_attn: true
freeze_classifier: true
model_type: wph

# training setting
dataset: liewyousheng/minc2500
deeper_path: minc-2500/images
resize: 360
classifier_epochs: 20
conv_epochs: 20
batch_size: 32
lr: 0.0001
lr_conv: 1.0e-5
lambda_reg: 1.0e+4
train_ratio: 0.1
test_ratio: 0.15
train_val_ratio: 2
seed: 42
vmap_chunk_size: 50
normalize_reg: false

# Classifier settings
num_classes: 23
use_batch_norm: true
copies: 1
noise_std: 0.01

