# This is a sweep config file for hyperparameter tuning on MNIST dataset
# It uses the base configuration from mnist.yaml and overrides specific parameters for the sweep
base_config: configs_wph/outex12.yaml
sweep:
  downsample: [true]
  train_ratio: [0.8]
  share_scale_pairs: [true]
  wavelet_params:
    - {S: 9, w0: 2.7646}  # 0.88 * pi
    - {S: 15, w0: 2.7646}  # 0.88 * pi
  copies: [1]
  freeze_classifier: [false]
  lr: [1.0e-2, 1.0e-3, 1.0e-4, 1.0e-5]
  lr_conv: [1.0e-3, 1.0e-4, 1.0e-5, 1.0e-6]
  fold: [2,1,0]


