# model setting
wavelet: morlet
max_scale: 3
nb_orients: 4
num_phases: 2
num_phases_prime: 1
random_filters: false
share_rotations: false
share_channels: true
share_phases: false
normalize_relu: true
delta_j: null
delta_l: null
shift_mode: samec
mask_union: false
mask_angles: 4
mask_union_highpass: true

# training setting
dataset: akash2sharma/tiny-imagenet
deeper_path: tiny-imagenet-200
classifier_epochs: 10
conv_epochs: 10
batch_size: 200
resize: 64
lr: 0.001
lambda_reg: 1.0e-3
train_ratio: 0.9
val_ratio: 0.1
seed: 42
vmap_chunk_size: 50

# Classifier settings
num_classes: 200
use_batch_norm: true

