# model setting
wavelet: morlet
max_scale: 3
nb_orients: 4
num_phases: 2
num_phases_prime: 1
random_filters: false
share_rotations: false
share_channels: true
share_phases: false
normalize_relu: true
delta_j: null
delta_l: null
shift_mode: samec
mask_union: false
mask_angles: 4
mask_union_highpass: true
# downsample: false (full-size), true (spatial downsampled), 'hybrid' (mixed downsampling/upsampling)
downsample: true
wavelet_params:
  S: 15
  sigma: 1.4
  xi: 1.57 # xi: 2.356 # xi: 1.57 # xi: 0.75 * pi 
# For hybrid mode, control signal downsampling per scale. Default: [j//2 for j in range(J)]
# Example: [0, 1, 2] means scales 0,1,2 get 2^0, 2^1, 2^2 signal downsampling
downsample_splits: null

# training setting
dataset: akash2sharma/tiny-imagenet
root_dir: $PROJECT_HOME/data/datasets/akash2sharma/tiny-imagenet
deeper_path: versions/1/tiny-imagenet-200
classifier_epochs: 15
conv_epochs: 15
batch_size: 200
resize: 64
lr: 0.001
lr_conv: 1.0e-6
lambda_reg: 1.0e+5
train_ratio: 0.8
test_ratio: 0.15
train_val_ratio: 2
seed: 42
vmap_chunk_size: 50

# Classifier settings
num_classes: 200
use_batch_norm: true

